### PR TITLE
Tweaks to messages and re-run notebooks

### PR DESCRIPTION
**Pull request by mirams**
1. Fix heighest -> highest
2. Fix some 'ordinals' ('st','nd','rd','th') with a fairly random bit of code I got off stackoverflow, but seems to work!
3. Re-run notebooks

### CODE REVIEW

**Comment by EricWay1024** [comment]
I ran `black` on the codebase to make the style check green

**Comment by EricWay1024** [comment]
> 2. Fix some 'ordinals' ('st','nd','rd','th') with a fairly random bit of code I got off stackoverflow, but seems to work!

I looked at the code and can confirm it is a valid algorithm

**Comment by MichaelClerx** [comment]
Bit overkill Eric!
Only a very small fraction of the changes that tool made were necessary. Especially the consistent use of ' instead of " is a conscious way of reducing RSI 😁

**Comment by MichaelClerx** [comment]
In general, good not to make any changes when you're reviewing too (because then those changes have not been reviewed!)

**Comment by MichaelClerx** [comment]
I'll re-open and revert some changes 😄

**Comment by EricWay1024** [comment]
Sorry I was too hasty in changing everything; thanks for the fixing! Will be careful next time

**Pull request merged**
